detectionName: 'template detection'
description: 'This is the detection used by online service'

metric: metric_to_monitor
dataset: dataset_to_which_this_metric_belongs

rules:
- detection:
  - name: detection_rule_1
    type: PERCENTAGE_RULE
    params:
      offset: wo1w
      percentageChange: 0.2
  filter:
  - name: filter_rule_1
    type: PERCENTAGE_CHANGE_FILTER
    params:
      pattern: UP_OR_DOWN
      threshold: 0.05
  quality:
  - name: data_sla_rule_1
    type: DATA_SLA
    params:
      sla: 3_DAYS
