apiVersion: v1
entries:
  pinot:
  - apiVersion: v1
    appVersion: 0.2.2
    created: "2020-09-29T00:03:26.751495-07:00"
    dependencies:
    - condition: pinot.zookeeper.enabled,zookeeper.enabled
      name: zookeeper
      repository: https://charts.helm.sh/incubator
      version: 2.1.3
    description: Apache Pinot is a realtime distributed OLAP datastore, which is used
      to deliver scalable real time analytics with low latency. It can ingest data
      from offline data sources (such as Hadoop and flat files) as well as online
      sources (such as Kafka). Pinot is designed to scale horizontally.
    digest: 7b571d881df299a83d5d351df562e81ec5e9d0ab0d2d4f7c2fd8622a997abde7
    home: https://pinot.apache.org/
    keywords:
    - olap
    - analytics
    - database
    - pinot
    maintainers:
    - email: dev@pinot.apache.org
      name: pinot-dev
    name: pinot
    sources:
    - https://github.com/apache/incubator-pinot
    urls:
    - pinot-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v1
    appVersion: 0.2.1
    created: "2020-09-29T00:03:26.748782-07:00"
    dependencies:
    - condition: pinot.zookeeper.enabled,zookeeper.enabled
      name: zookeeper
      repository: https://charts.helm.sh/incubator
      version: 2.1.3
    description: Apache Pinot is a realtime distributed OLAP datastore, which is used
      to deliver scalable real time analytics with low latency. It can ingest data
      from offline data sources (such as Hadoop and flat files) as well as online
      sources (such as Kafka). Pinot is designed to scale horizontally.
    digest: 605b74fb6203f62500638fd679859cc771ca37ed420f89e02a0c82c3ede92690
    home: https://pinot.apache.org/
    keywords:
    - olap
    - analytics
    - database
    - pinot
    maintainers:
    - email: dev@pinot.apache.org
      name: pinot-dev
    name: pinot
    sources:
    - https://github.com/apache/incubator-pinot
    urls:
    - pinot-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v1
    appVersion: 0.2.0
    created: "2020-09-29T00:03:26.745494-07:00"
    dependencies:
    - condition: pinot.zookeeper.enabled,zookeeper.enabled
      name: zookeeper
      repository: https://charts.helm.sh/incubator
      version: 2.1.3
    description: Apache Pinot is a realtime distributed OLAP datastore, which is used
      to deliver scalable real time analytics with low latency. It can ingest data
      from offline data sources (such as Hadoop and flat files) as well as online
      sources (such as Kafka). Pinot is designed to scale horizontally.
    digest: a15cb08e2077d6e2893ea46212a5b769f303af83904681a95e550879fa22f870
    home: https://pinot.apache.org/
    keywords:
    - olap
    - analytics
    - database
    - pinot
    maintainers:
    - email: dev@pinot.apache.org
      name: pinot-dev
    name: pinot
    sources:
    - https://github.com/apache/incubator-pinot
    urls:
    - pinot-0.2.0.tgz
    version: 0.2.0
  presto:
  - apiVersion: v1
    appVersion: 0.2.0
    created: "2020-09-29T00:03:26.753701-07:00"
    description: Presto is an open source distributed SQL query engine for running
      interactive analytic queries against data sources of all sizes ranging from
      gigabytes to petabytes.
    digest: d17eb6e0b1b3ba26e013325d7fb8da1c7a25fad35f37f955f4fbe402b5363b15
    home: https://github.com/prestodb/presto
    keywords:
    - analytics
    - database
    - presto
    maintainers:
    - email: dev@pinot.apache.org
      name: pinot-dev
    name: presto
    sources:
    - https://github.com/apache/incubator-pinot/tree/master/kubernetes/helm
    urls:
    - presto-0.2.0.tgz
    version: 0.2.0
generated: "2020-09-29T00:03:26.739572-07:00"
